---
- name: create oracle temp dir for installer
  file: path={{ oracle_tmp }} state=directory mode=0775

- name: get oracle installer
  get_url:
    url: "{{ oracle_installer_uri }}/{{ installer }}"
    dest: "{{ oracle_tmp }}/{{ installer }}"

- name: verify installer checksum
  command: cksum {{ oracle_tmp }}/{{ installer }}
  register: installer_check
  failed_when: "installer_check.stdout.find('{{ checksum }}') != 0"

- name: last filename in zipfile
  shell: jar -tf {{installer}} | tail -1
  args:
    chdir: "{{oracle_tmp}}"
  register: lastfile

- name: unzip installer
  unarchive: src={{ oracle_tmp }}/{{ installer }} dest={{ oracle_tmp }} copy=no creates="{{oracle_tmp}}/{{lastfile}}"
